### ISSUE TITLE
Name issues / upload to pypi

### ISSUE THREAD

**Issue by nikolas** [mpasternak/django-interval-field#12]
* The title of this repo is `django-interval-field`, but the package name in `setup.py` is `django-pgsql-interval-field`.
* This package isn't on pypi. Could you upload it?

**Comment by mpasternak** [comment]
Of course. Feel free to submit a pull req.  Patches welcome

śr., 1 lip 2015, 20:40 Nik Nyby użytkownik <notifications@github.com>
napisał:

**Comment by nikolas** [comment]
I can't submit a patch request to upload to pypi - the package owner needs to do it.

**Comment by mpasternak** [comment]
You can.

śr., 1 lip 2015, 21:02 Nik Nyby użytkownik <notifications@github.com>
napisał:

**Comment by nikolas** [comment]
What if I don't want to? lol

**Comment by nikolas** [comment]
what if i thought maybe you want to be the owner

**Comment by nikolas** [comment]
Should the name be django-interval-field or django-pgsql-interval-field?

**Comment by mpasternak** [comment]
Why does it matter to you?
2 lip 2015 00:04 "Nik Nyby" <notifications@github.com> napisał(a):

**Comment by mpasternak** [comment]
I'm asking, because for my needs it really doesn't matter... and, if it works - for me - introducing such change may include extra hassle _without_ any perceived benefits - for me - right now.

Also, bear in mind, that Django has interval field support for PostgreSQL since 1.8 or so. It may be different than this field and people may still want to use this package, especially if they are already using it, but examining the options of Django 1.8 and preparing a migration path for current users might be a better option to introduce right now. 

And, having this in mind, there's not much sense in adding this package to PyPI. Unless you want to have this package as a form of backport or such, backwards-compatibility layer, you name it. BUT there is django-compat already, maybe there's more sense doing some work there, backporting 1.8 functionalities to previous versions, if you need it.

Having this in mind, I perceive this package more as a legacy package. I created it, worked on it, it worked very well for 2 of my projects, now Django supports it since 1.8 and this package is no longer needed.

**Comment by nikolas** [comment]
One of my applications uses Django 1.8, but still uses django-interval-field. I don't know how to migrate from django-interval-field to Django 1.8's DurationField, so I'd like to continue using this package, which is why I want to put it on pypi. Could you merge #13 and #7, or do you have alternatives? I agree that this is really a 'legacy' package. I would like to convert to django 1.8's DurationField, but how? https://github.com/ccnmtl/dmt/blob/master/dmt/main/models.py#L938

**Comment by mpasternak** [comment]
#7 merged, thanks.

I'm not planning PyPI release, if you plan to do that, please fork this project.
